### ISSUE TITLE
Blank Page in PHP7 / User not in sudoers (on Arch Linux)

### ISSUE THREAD

**Issue by mozzieongit** [EmerickH/VBAN-manager#2]
**Solution** 

To use the VBAN-manager you need a version of PHP5 (probably beginning at 5.4 | I use PHP5.6, as PHP7 isn't able to use old function parameters like ```this```)
You also need to check which dedicated user your Apache installation uses (on Arch Linux it's ```http``` so you edit the /etc/sudoers.d/mount file to ```http ALL=(ALL:ALL) NOPASSWD:/var/www/html/script/vban.sh``` instead of ```www-data ALL=(ALL:ALL) NOPASSWD:/var/www/html/script/vban.sh``` as shown [here](https://github.com/VBAN-manager/VBAN-manager))
Now the website and the script should work. If you have an audio device error in the emitter, wait till we have a Solution (smile)

Original:
Which PHP Version is needed?
When I try to add a server i get a blank page. (the URL is: http://localhost/server.php?id=2&new=true)
The initial site seems working fine. (when opening localhost)

**Comment by EmerickH** [comment]
Hello @mozzieongit,
thank you for reporting your problem, unfortunately I don't remember the version I used on my Raspberry, probably a recent PHP5 one. Which version are you trying to use?
Can you copy/paste the errors shown in `/var/log/apache2/php.log` (or maybe in `/var/log/apache2/error.log`)?

Emerick

**Comment by mozzieongit** [comment]
Hello Emerick,
I'm using PHP7. The content of `/var/log/httpd/error_log` is (httpd instead of apache | I use Arch Linux):
> [Sun Jan 06 17:36:52.574275 2019] [mpm_event:notice] [pid 13170:tid 139935963487168] AH00489: Apache/2.4.37 (Unix) configured -- resuming normal operations
[Sun Jan 06 17:36:52.574368 2019] [core:notice] [pid 13170:tid 139935963487168] AH00094: Command line: '/usr/bin/httpd -D FOREGROUND'
[Sun Jan 06 17:53:31.508919 2019] [mpm_event:notice] [pid 13170:tid 139935963487168] AH00492: caught SIGWINCH, shutting down gracefully
[Sun Jan 06 17:53:34.718118 2019] [mpm_prefork:notice] [pid 13469] AH00163: Apache/2.4.37 (Unix) PHP/7.3.0 configured -- resuming normal operations
[Sun Jan 06 17:53:34.718157 2019] [core:notice] [pid 13469] AH00094: Command line: '/usr/bin/httpd -D FOREGROUND'
[Sun Jan 06 17:53:41.956165 2019] [php7:error] [pid 13471] [client ::1:52716] PHP Fatal error:  Cannot use $this as parameter in /srv/http/server.php on line 9, referer: http://localhost/
[Sun Jan 06 18:07:57.278104 2019] [php7:error] [pid 13475] [client ::1:52916] PHP Fatal error:  Cannot use $this as parameter in /srv/http/server.php on line 9, referer: http://localhost/index.php
[Sun Jan 06 18:25:57.191082 2019] [php7:error] [pid 13486] [client ::1:53204] PHP Fatal error:  Cannot use $this as parameter in /srv/http/server.php on line 9, referer: http://localhost/
[Sun Jan 06 20:21:09.846759 2019] [mpm_prefork:notice] [pid 13469] AH00169: caught SIGTERM, shutting down

I'll be trying to install an older version of PHP and try again. As the error log shows, `$this` is an invalid parameter. Maybe that is because PHP7.

mozzie

**Comment by mozzieongit** [comment]
Hello Emerick,
I found the solution. I Installed PHP5.6, managed to get it working with Apache (Apache couldn't load the Module...) and now the "New Server"-Site works. PHP7 seems to be uncomfortable with old function parameters.
The errors show, that the user is not in sudoers, but I'll fix that myself.

mozzie

**Comment by mozzieongit** [comment]
Hi Emerick, it's me, again. I added the apache user to the sudoers, but now the error says that `http` (the user) has no password. I added one and it couldnt authenticate (I couldn't figure out how to provide a user passwd in apache config.
Do you have any idea?

**Comment by EmerickH** [comment]
@mozzieongit have you followed [this](https://github.com/VBAN-manager/VBAN-manager#install)?

**Comment by mozzieongit** [comment]
@EmerickH 
Yes. Do I have to change the permissions or ownage of the mount file with chmod? (Currently rw r r / root:root)  

What does the "www-data" part stand for?

**Comment by EmerickH** [comment]
Try `chown www-data:www-data scriptname.sh`
**www-data** is the user apache2 uses to run
(so the sudoer line should be exactly `www-data ALL=(ALL:ALL) NOPASSWD:/var/www/html/script/vban.sh` and not your user)

**Comment by mozzieongit** [comment]
I changed www-data to http (thats the only user i can associate with apache). It works!
Now I get the error that the alsa backend is busy (when emitting). When I enter the command from args-2.txt in the terminal it works fine.

Log (Level 0) from localhost-site: 
`Started
ALSA lib pcm_dsnoop.c:638:(snd_pcm_dsnoop_open) unable to open slave
Fatal: alsa_open: open error: Device or resource busy
vban_emitter version 2.1.0

Stopped`

**Comment by EmerickH** [comment]
Ok, I didn't know that some version of apache are using `http` user..
Can you copy/paste args-2.txt? Have you got any software running which can also use sound?
(I personally never got vban_emitter working with a "complex" device, but this is a vban emitor bug: https://github.com/quiniouben/vban/issues/21)

**Comment by mozzieongit** [comment]
I'm running Arch Linux, btw.
args-2.txt: `emitter -i 192.168.0.22 -p 6980 -s Stream1 -b alsa -l 0`
I used vban_$(cat args-2.txt) to "copy" the command into my terminal.
> Have you got any software running which can also use sound?

What do you mean by that? Pulseaudio and Jack (Bridge: Alsa > Pulse > Jack)?

**Comment by EmerickH** [comment]
Ok try to precise the device you want to use in "Audio device" texbox on server config (default alsa device may not be set for http user).
If I remember well, it's a PCM name that you can get with `aplay -L` (something like plughw:CARD=XXXX,DEV=X, or if it's not working hw:CARD=XXXX,DEV=X)

**Comment by mozzieongit** [comment]
Now its a bit less, then before:
`Started`
`Fatal: alsa_open: open error: Device or resource busy`
`vban_emitter version 2.1.0 `

I'll be back in a few days. I have to shutdown now.

**Comment by EmerickH** [comment]
Ok, this message is saying that you have an other opened process (maybe another instance of vban_emitor?) that is using the PCM at the same time (alsa can only have 1 software accessing a PCM at the same time!)

**Comment by mozzieongit** [comment]
There was no other instance of vban_emitter. I tried to test it with a Loopback device (modprobe snd-aloop) Now I don't get the "resource busy" part. Instead: `Error: main: packet prepared is invalid` (is that due to the loopback device [Edit: I tried in terminal... it's because of the loopback]; I will try with my external USB Soundcard, tomorrow.) The funny thing is, that the device (main soundcard - hw:PCH,0) doesn't "seem" busy when I insert the same command in Terminal, as stated before :)

**Comment by mozzieongit** [comment]
Btw. Is it possible to move a part of comments on an issue to another issue? I think its pretty confusing to split the problems up, if someone has one of them.

**Comment by EmerickH** [comment]
Hello, no we can't move comments but that's a good idea to create a new issue, can you precise the name of the PCM you want to use ?

**Comment by EmerickH** [comment]
Just remembered a thing, try:
```
 sudo adduser http audio
```
(and if you're using pulseaudio output:) 
```
sudo adduser http pulse-access
sudo adduser http pulse-access
```
(if it's working I will edit Readme to include everything on this issue, no need to create a new one)

**Comment by mozzieongit** [comment]
Sorry, what is PCM?
