### ISSUE TITLE
Audio Resource is busy (vban_emitter with alsa)

### ISSUE THREAD

**Issue by mozzieongit** [EmerickH/VBAN-manager#3]
Continues issue #2 

**EDIT FROM MAINTAINER:** See [dedicated wiki section](https://github.com/VBAN-manager/VBAN-manager/wiki/Known-bugs#possible-issue-2)

**Comment by EmerickH** [comment]
Did you try https://github.com/VBAN-manager/VBAN-manager/issues/2#issuecomment-457492072 ? The PCM is the audio device name you get with aplay -L (see https://github.com/VBAN-manager/VBAN-manager/issues/2#issuecomment-456970693)

**Comment by mozzieongit** [comment]
Yes, it didn't work. And I don't have a pulse-access group or any group that has the name "pulse" in it.

I tried to use this device:
```
front:CARD=PCH,DEV=0
   HDA Intel PCH, ALC255 Analog
    Front speakers
```
also in the name-"variants": `hw:0,0` and `plughw:0,0`and `hw:PCH,0` (those names worked in jack)

**Comment by EmerickH** [comment]
It should be the plughw (no samplerate conversion) I think,
I just realized that the script is run with sudo, try:
```
 sudo adduser root audio
```
(or the user used by sudo command in ArchLinux)

**Comment by mozzieongit** [comment]
Even when added root to audio it doesn't work.
Why does the script even need sudo/root? When I run it in terminal I don't use sudo. I tried adding http to users (group) but no success. Where can I change the script to not use sudo?

**Comment by EmerickH** [comment]
Honestly I don't remember why I used sudo, try to remove all 
```
"sudo " .
```
 in php files:
- action.php
- plugin_action.php
- modify_args.php
 and be shure that whole fonder is chown to http 

OR
Another solution may be to edit script and modify
```
su - youruser -c "vban_.... "
```

**Comment by mozzieongit** [comment]
I'm not sure where to put the quotation marks... now it's: ```su - mozzie -c "vban_`cat args-$2.txt` &>> log-$2.txt &"```
But that doesn't work as it is a string in the shell-script, right?

**Comment by EmerickH** [comment]
Try
```
su - mozzie -c "vban_$(cat args-$2.txt) &>> log-$2.txt &"
```

**Comment by mozzieongit** [comment]
Ok, did that.
In the script folder the 2.pid file is now empty and the log just says started and stopped... I think that doesn't work. Maybe because of the password?

**Comment by mozzieongit** [comment]
I'd guess that the method of editing the PHP files won't work either (at least with pulseaudio) because pulseaudio dynamically allows user accounts to control it's applications (just the one, that is logged in).
So the problem might be in the user selection (su - username -c "...") where no password can be passed and in pulseaudio.

**Comment by mozzieongit** [comment]
I have no Idea why, but my css for the VBAN-manager died... its just plain html now

**Comment by EmerickH** [comment]
I'm back home this week-end so I think I will fix my code to be launched by user (via a service) tonight (in France it's actually) or maybe in the we.
For the CSS, check console: right click on page>Inspect element

**Comment by mozzieongit** [comment]
Ok.
It says "No CSS properties found." And "Loading failed for the <script> with source “http://localhost/js/jquery.min.js”." (For the files jquery.min.js , bootstrap.min.js , scripts.js in js/)

**Comment by EmerickH** [comment]
Ok, that's strange, and for the bug I've maybe found: vban_receptor/emiter, even if you don't use pulseaudio is searching for pulseaudio server which need to be launched in system-wide (`sudo pulseaudio --system`) mode to be accessible in a script, I have no idea why it is creating Alsa errors too but it's solving this issue for me:
```
janv. 25 21:35:14 raspaudio pulseaudio[1931]: [pulseaudio] server-lookup.c: Unable to contact D-Bus: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
janv. 25 21:35:14 raspaudio pulseaudio[1931]: [pulseaudio] main.c: Unable to contact D-Bus: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
janv. 25 21:35:14 raspaudio pulseaudio[1931]: [pulseaudio] bluez4-util.c: org.bluez.Manager.GetProperties() failed: org.freedesktop.DBus.Error.UnknownMethod: Method "GetProperties" with signature "" on interface "org....er" doesn't exist
janv. 25 21:35:14 raspaudio sh[1921]: Fatal: alsa_open: open error: Device or resource busy
janv. 25 21:35:14 raspaudio sh[1921]: Error: audio_set_stream_config: could not open backend with new config
```
If you don't use pulseaudio, ~~you can compile vban_xxx without pulseaudio support, that's simpler~~
_even with --disable-pulseaudio --disable-jack it still searching for pa server_
**You have to disable pulse by setting autospawn to no in /etc/pulse/client.conf and `killall pulseaudio` or simply uninstall pulseaudio**

### -> See https://github.com/VBAN-manager/VBAN-manager/wiki/Known-bugs#possible-issue-2 to install system-wide PA

**Comment by EmerickH** [comment]
Done! Pull the latest version of the repository (`git pull`, maybe also `git reset --hard origin` if you made modifications and then `git pull` again). See [wiki](https://github.com/VBAN-manager/VBAN-manager/wiki/Installation) for installing new system.

**Comment by mozzieongit** [comment]
> You have to disable pulse

or
> pulseaudio server which need to be launched in system-wide mode

That's unfortunate, as my desktop environment relies on PulseAudio. I also use the Alsa > Pulse > Jack Bridge that wouldn't work in system-wide mode (as stated on freedesktop.org PulseAudio Documentation). I guess I'll use the terminal then. But thanks for your help and effort on that.

mozzie

**Comment by mozzieongit** [comment]
You might want to add the needed version of PHP to your installation wiki.
