### ISSUE TITLE
Project licence?

### ISSUE THREAD

**Issue by henrikp** [EmerickH/VBAN-manager#5]
Hi, I wish to make a package out of this project to complement the vban suite but sadly I can't add it anywhere due to no licence. Can you select one for this project?

**Comment by EmerickH** [comment]
Hi,
Totally forgot to add a license for this project!
I just added an Apache licence 2.0 in commit https://github.com/VBAN-manager/VBAN-manager/commit/5d1d5f888ff1d222dffd931aea5828f62d1c4c48
In what kind of package do you want to add VBAN-manager?

**Comment by henrikp** [comment]
I have the foundation laid out for a Gentoo package, have to research a bit how similar packages are done. Nothing impossible :)

**Comment by EmerickH** [comment]
Ok, the difficulty of packaging VBAN-manager is that it's not a software but a web application relying on apache and PHP, a solution could be to put A2/PHP on dependency list, to put VBAN-manager in a special folder (something like /opt/VBAN-manager/) and automaticaly add a configuration to Apache2 to virtualhost anything.com/VBAN-manager to /opt/VBAN-manager/, exactly like PHPmyAdmin does
